{
	"_id" : ObjectId("50c678a043b67c0d6bebfd97"),
	"_class" : "com.gtc.pfm.domain.Package",
	"name" : "test",
	"exp" : ISODate("2012-12-11T00:04:46.741Z"),
	"own" : {
		"_id" : ObjectId("507f1f77bcf86cd799439011"),
		"un" : "serhat"
	},
	"rcpt" : {
		"_id" : ObjectId("507f1f77bcf86cd799439012"),
		"un" : "serhat"
	},
	"vr" : {
		"_id" : ObjectId("507f1f77bcf86cd799439013"),
		"name" : "Aura",
		"t" : 2,
		"coN" : "Turkey",
		"ciN" : "Antalya",
		"l" : [
			52.531261,
			13.405838
		]
	},
	"t" : 2,
	"o" : false
}